### ISSUE TITLE
Geiles Projekt!

### ISSUE THREAD

**Issue by soundglider** [booya-at/OpenGlider#10]
Ich fuchs mich mal in deinen Code rein... würde gerne mithelfen! Momentan funzts bei mir unter Ubuntu noch nicht, vtk gibt mir einen Symbol Error:
# 
## ERROR: visual_test_glider (unittest.loader.ModuleImportFailure)

ImportError: Failed to import test module: visual_test_glider
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/home/lc1bseba/DEVELOP/OpenGlider/tests/visual_test_glider.py", line 30, in <module>
    import openglider.Graphics
  File "/home/lc1bseba/DEVELOP/OpenGlider/openglider/Graphics/**init**.py", line 22, in <module>
    from openglider.Graphics.Functions import Graphics2D, Graphics3D, Graphics, Line, Point, Polygon, listlineplot, Axes, draw_glider
  File "/home/lc1bseba/DEVELOP/OpenGlider/openglider/Graphics/Functions.py", line 22, in <module>
    import vtk
  File "/usr/lib/pymodules/python2.7/vtk/**init**.py", line 43, in <module>
    from vtkIOPython import *
ImportError: /usr/lib/libvtkIOPythonD.so.5.8: undefined symbol: _ZN21vtkPostgreSQLDatabase3NewEv

**Comment by hiaselhans** [comment]
heyho! sehr cool!!
also vtk,
ich habe leider kein ubuntu aber der lorenz hat einfach mit apt-get das paket python-vtk installiert und es funktioniert bei ihm... :)
welche version verwendest du?

lg!

**Comment by soundglider** [comment]
Keine Ahnung, ich habs auch einfach mit apt-get installiert, ich weiß nicht, was da schief gelaufen ist... ich verwende Ubuntu 12.10 LTS

**Comment by looooo** [comment]
mit 12.04, 13.04, 13.10 funktioniert es bei mir. 12.10 hab ich leider nicht mehr.

**Comment by soundglider** [comment]
Liegt wahrscheinlich an meinem System, hab hier ne handkompilierte Version von vtk, die evtl. meine paketversion zerstört hat... ich arbeite daran.

**Comment by soundglider** [comment]
Ok, läuft! Jetzt funktionierts. Hab alle überbleibsel von meiner selbstkompilierten VTK-Version entfernt und die Pakete genommen...

**Comment by hiaselhans** [comment]
:)
