### ISSUE TITLE
missing line input

### ISSUE THREAD

**Issue by looooo** [booya-at/OpenGlider#15]
a glider can't fly without lines! there is missing a graphical line input tool!!!
# To Do
- [x] glider2d storing linedata
- [x] save 2d line data (json)
- [x] event callback for deleting lines and linepoints
- [x] object widget
- [x] input for target length
- [x] multi selection for line inputs
- [x] inputs for lower attachment point (x, y z)
- [x] input for line_type
- [ ] get a nice table of line data + drawing
- [x] create layers

**Comment by looooo** [comment]
![bildschirmfoto vom 2014-11-15 16 45 34](https://cloud.githubusercontent.com/assets/5084704/5233070/6bd33e02-7769-11e4-81d3-0315b56b8f34.png)

**Comment by hiaselhans** [comment]
:+1:

**Comment by looooo** [comment]
freecad-related stuff is now here: https://github.com/looooo/freecad_glider

**Comment by looooo** [comment]
freecad-related stuff is now here: https://github.com/looooo/freecad_glider
