### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by Mx74** [booya-at/OpenGlider#37]
("Non-ASCII character '\\xc3' in file /home/max/OpenGlider/freecad/freecad_glider/tools/__init__.py on line 54, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details", ('/home/max/OpenGlider/freecad/freecad_glider/tools/__init__.py', 54, 0, None))
Traceback (most recent call last):
  File "/home/max/OpenGlider/freecad/freecad_glider/init_gui.py", line 101, in Initialize
    from . import tools

**Comment by looooo** [comment]
thanks for reporting, should be fixed with https://github.com/booya-at/OpenGlider/commit/d65551a87a5be25fd4bc3472a56c5be131c687d9
