### ISSUE TITLE
Can't select any point

### ISSUE THREAD

**Issue by Mx74** [booya-at/OpenGlider#38]
Hello,

Hello, I have a weird issue, not sure it related to OpenGlider... but I ask anyway:

The workbench seems to work ok, but on any tool that needs to work with the mouse (shape, lines, design, etc...) I can't select any item. 
When I click on a point, the cursor change from an arrow to the hand, but the point isn't catched, and I can't move anything...

Last commit working on Freecad-daily

**Comment by looooo** [comment]
We have seen a similar issue and it was to due a pivy bug. If I remeber correctly it was due to swig 4.0 not adding some basic wrappers. This should be solved with latest pivy version. https://github.com/FreeCAD/pivy/releases/tag/0.6.5a2
