### ISSUE TITLE
meshpy missing from the requires.txt

### ISSUE THREAD

**Issue by goatchurchprime** [booya-at/OpenGlider#46]
I was installing using `pip install -e .` and then manually installing the dependencies, and this was the library it needed to run the testall.py.

I was trying to avoid the conda install route, because I can't tell where it will load the project from and where it would put it, or how out of date that version would be.  Nevertheless I had to do this as there were no instructions for how to get this code to show up as a FreeCAD workbench.

**Comment by looooo** [comment]
Conda is not that difficult. you can have everything installed in the user directory.
anyway, meshpy should be available from pypi too.

**Comment by hiaselhans** [comment]
thx @goatchurchprime !

i added meshpy to the requirements with d37a6189ffb6a7cea45f739b4d82d31c66bf9f4c
